name: SDK Matrix

on:
  pull_request:
  push:
    branches: [main, feat/sdk-generator]

jobs:
  python-sdk:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Generate SDKs
        run: pnpm run sdk:generate

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python test deps
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema pytest rich

      - name: Run Python tests
        run: pytest packages/aid-core-py/tests -q
        env:
          PYTHONPATH: packages/aid-core-py

  go-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Generate SDKs
        run: pnpm run sdk:generate

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Run Go tests
        run: |
          cd packages/aid-core-go
          go test ./... 