name: SDK Matrix

on:
  pull_request:
  push:
    branches: [main, feat/sdk-generator]

jobs:
  # Job 1: Setup and generate the code ONCE
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install pnpm and dependencies
        uses: pnpm/action-setup@v3
        with:
          version: 8
          # This will run `pnpm install` and correctly configure the PATH
          run_install: true

      - name: Generate All SDKs
        run: pnpm run sdk:generate

      - name: Upload Generated SDKs as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-sdks
          path: .

  # Job 2: Test the Python SDK
  python-sdk:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]
    steps:
      - name: Download Generated SDKs
        uses: actions/download-artifact@v4
        with:
          name: generated-sdks

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies and run tests
        run: |
          python -m pip install -r packages/aid-core-py/requirements.txt
          python -m pip install -e packages/aid-core-py
          pytest packages/aid-core-py/tests

  # Job 3: Test the Go SDK
  go-sdk:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Download Generated SDKs
        uses: actions/download-artifact@v4
        with:
          name: generated-sdks

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Run Go tests
        run: |
          cd packages/aid-core-go
          go test ./...