name: Sync AID Schema to Docs

on:
  push:
    branches:
      - main
    paths:
      - 'schema/v1/aid.schema.json'

jobs:
  sync-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout AgentInterfaceDiscovery Repo
        uses: actions/checkout@v4

      - name: Checkout Docs Repo
        uses: actions/checkout@v4
        with:
          repository: agentcommunity/docs
          path: ./docs-repo
          # A Personal Access Token with repo scope is required
          # It should be stored as a secret named DOCS_REPO_PAT
          token: ${{ secrets.DOCS_REPO_PAT }}

      - name: Copy Schema to Docs Repo
        run: |
          mkdir -p ./docs-repo/docs/specs/aid
          cp ./schema/v1/aid.schema.json ./docs-repo/docs/specs/aid/aid.schema.json
          echo "Schema file copied to docs/docs/specs/aid/aid.schema.json"

      - name: Commit and Push to Docs Repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./docs-repo
          commit_message: "chore(schema): Sync latest aid.schema.json"
          commit_user_name: "AID Schema Bot"
          commit_user_email: "actions@github.com"
          commit_author: "AID Schema Bot <actions@github.com>"
          push_options: '--force' # Use force push if you want to overwrite history, otherwise remove. For this use-case it might be okay. 